### ISSUE TITLE
update references on Fable.React and Fable.React.Types packages, or on Feliz 

### ISSUE THREAD

**Issue by romanstetsenko** [uxsoft/Fable.Builders.AntDesign#1]
Hi. First of all, thank you for your packages!

Recently Fable.React was divided into two packages - Fable.React and Fable.React.Types. And now every usage of `Fable.Builders.AntDesign`  leads to broken intellisense and the error:
_The module/namespace 'Fable.React' from compilation unit 'Fable.React' did not contain the namespace, module or type 
'ReactElement'_

Could you update references on Fable.React and Fable.React.Types packages, or on Feliz package 2.0.0-prerelease-003 which fixed the same issue ?

Sample of code
`open Fable.Builders.AntDesign

let b = Button {
    str "Button"
}`

**Comment by uxsoft** [comment]
I'll take a look at it, thanks!

**Comment by uxsoft** [comment]
Hi, I tried removing all mentions of Fable.React and thus migrating to Feliz. Try if it works for you and let me know.

**Comment by romanstetsenko** [comment]
It works for both cases - with split packages or with just older Fable.React.
Thank you!
